# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - release/*

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Enable Corepack
        run: |
          corepack enable
          node -v
          yarn --version

      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Publish
        run: |
          yarn config set npmAuthToken ${{secrets.NPM_TOKEN}}
          yarn publish
